package com.lunchup

object LunchupContent {
  val roleAndLunchBuddy = List( 
      "Jake Levine,Dev,rich hsieh,Adrian Parsons,Evan Estola,,,,,,",
      "Brian Gruber,Dev,Yvette Pasqua,Adam Detrick,,,,,,,",
      "Kristen Stewart,Design,Jen Gergen,Jose Rodriguez,Byron Hulcher,Daron Lin,,,,",
      "Chris Austin,Design,Jen Gergen,,,,,,,,",
      "Wayne Folkes,Systems,Qing Shou,Brandon Price,Ian Corbett,Qing Shou,,,,,",
      "Nicole Maslov,HR,Erin Dertouzos,Ella Creedy-Hall,Caroline Marcks,Nora Lorenzo,,,,,",
      "Bryan Velzy,Community,Dana Wolma,Aashish Srinivas,Vlad Burca,Lilith Ben-Or,,,,,",
      "Laura Ragone,Dev,Will Howard,Paul Bruneau,Brian Capps,,,,,,",
      "Jeff Campbell,Dev,Gavin Maisel,Byron Hulcher,Anne DeCusatis,Brian Gruber,,,,,",
      "Marina Tempelsman,Strategy,Brian Lafayette,Emily Swanson,,,,,,,",
      "nlatorre@meetup.com,Community,Jenn Louie,Amy Classen,Troy Cox,,,,,,",
      "David Anderson,Community,Andrew Williams,Troy Cox,,,,,,,",
      "Emily Swanson,Community,Andrew Williams,Ann Nguyen,Samantha Schwartz,Marina Tempelsman,,,,,",
      "Anne DeCusatis,Dev,Jose Rodriguez,Byron Hulcher,Coralie Pachaud,,,,,,",
      "Nora Lorenzo,HR,Erin Dertouzos,Nicole Maslov,Ella Creedy-Hall,Michelle Heng,,,,,",
      "Caroline Marcks,Dev,Jake Levine,Nicole Maslov,Ella Creedy-Hall,Katie Lahey,,,,,",
      "Paul Bruneau,Dev,Will Howard,Brian Capps,Laura Ragone,,,,,,",
      "David Jimenez,Community,Dana Wolma,David Anderson,Hakiem Simmons,Ann Nguyen,,,,,",
      "caitlyn@meetup.com,Community,Andrew Williams,Katie Lahey,,,,,,,",
      "Lydia Kopecky,Community,Andrew Williams,Marc Leone,Nicole Maslov,,,,,,",
      "Kelty Niles,Strategy,Brian Lafayette,Alex Godin, Victor,,,,,,,",
      "Michelle Heng,HR,Erin Dertouzos,Nicole Maslov,Nora Lorenzo,Erin Dertouzos,,,,,",
      "Andrew Williams,Community,Dana Wolma,Scott D'Antuono,Sarah Jean Billeiter,Deirdre Johnson,,,,,",
      "Alex Godin,,,,,,,,,,",
      "Adam Lippman,Product,Fiona Spruill,Jose Rodriguez,Daron Lin,Mike Spencer,Rich Hsieh,Kristen Stewart,Matt Trush,Michael Curtes,Odile",
      "Mike Perrotti,Design,,,,,,,,,",
      "Hannah Bock,T & S,Jenn Louie,Amy Classen,Nicole LaTorre,Troy Cox,,,,,",
      "Laura Blackett,International,Rachel Lafayette,,,,,,,,",
      "Ann Nguyen,Community,Andrew Williams,Emily Swanson,Samantha Schwartz,Ryan Rosa,,,,,",
      "Sarah Jean Billeiter,Dev,Gavin Maisel ,Scott D'Antuono,Andrew Williams,,,,,,",
      "Maki Yamamoto,Community,Andrew Williams,Nan Li,Sak Lee,,,,,,",
      "Deirdre Johnson,Community,Dana Wolma ,Marina Tempelsman,Andrew Williams,Emily Swanson,,,,,",
      "Gavin Maisel,Dev,Will Howard,Scott D'Antuono,Sarah Jean Billeiter,Will Howard,,,,,",
      "Doug Tangren,Dev,brian,,,,,,,,",
      "Coralie Pachaud,International,Odile Beniflah,Romy Roloff,Ben Tumin,,,,,,",
      "Matthew Holloman,triforce,Ryan Rosa,,,,,,,,",
      "Odile Beniflah,International,Fiona Spruill,Coralie Pachaud,Brian Lafayette,Amy Classen,,,,,",
      "Ella Creedy-Hall,Community,Andrew Williams,Caroline Marcks,Nicole Maslov,Katie Lahey,,,,,",
      "Katie Lahey,T&S,Jenn Louie,Juan Leguizamon,Ella Creedy-Hall,David Anderson,,,,,",
      "Evan Estola,Dev,brian gruber,Adrian Parsons,Aashish Srinivas,,,,,,",
      "Erin Rauch-Sasseen,Community,Dana Wolma,Samantha Schwartz ,,,,,,,",
      "Kara Donaldson,Community,Dana Wolma,Nicole Latorre,,,,,,,",
      "Jacob Roa,Community,Dana Wolma,Bryan Velzy,,,,,,,",
      "Sarah Cassidy,Community,Andrew Williams,,,,,,,,",
      "Daron Lin,Dev,Chris Lewis,Calvin Hu,Jose Rodriguez,Mike Spencer,,,,,",
      "Vlad Burca,Dev,Jake Levine,Aashish, Mike S, Bryan V,,,,,,,",
      "Adaam Hukins,Dev,Gavin Maisel,Scott D'Antuono,Sarah Jean Billeiter,,,,,,",
      "Marc Leone,Trust & Safety,Jenn Louie,Scott D'Antuono,Ella Creedy-Hall,Hannah,,,,,",
      "Michael Curtes,Product,Fiona Spruill,Farah Assir,Nick Stamas,Rick Boenigk,,,,,",
      "Yvette Pasqua,Dev,Scott Heiferman,Andres Glusman,Fiona Spruill,Scott Heiferman,,,,,",
      "Matt Kime,Dev,Sadaf Shahsahebi,Adam Detrick,,,,,,,",
      "Romy Roloff,Community,Dana Wolma,Juan Leguizamon,Natalia Marmolejo,Victor Longo,,,,,",
      "Sadaf Shahsahebi,Dev,Will Howard,,,,,,,,",
      "Adam Detrick,Dev,Ivy Feraco,Brian Gruber,Matt Kime,,,,,,",
      "Natalia Marmolejo,Design,Jen Gergen,Romy Roloff,Farah Assir,Nick Stamas,,,,,",
      "Andrea Murphy,Community,Dana Wolma,,,,,,,,",
      "Jose Rodriguez,Dev,rich hsieh,Adam Lippman,Daron Lin,Mike Spencer,,,,,",
      "Hakiem Simmons,Finance,Julia Brodatska,Scott D'Antuono,Julia Brodatska,David Jimenez,,,,,",
      "Amy Classen,Trust and Safety,Jenn Louie ,Marina Tempelsman,Nicole Maslov,Hannah Bock,Odile Beniflah,,,,",
      "Anna Armentrout,Dev,Sadaf Shahsahebi,Will Carlough,Ivy Feraco,,,,,,",
      "Brian Lafayette,Strategy,Andres Glusman ,Alex Godin,Andres Glusman,,,,,,",
      "Scott D'Antuono,Dev,Gavin Maisel,Sarah Jean Billeiter,Hakiem Simmons,Andrew Williams,,,,,",
      "Victor Longo,International,Odile Beniflah,Romy Roloff,Natalia Marmolejo,Coralie Pachaud,Victoria Karunarathna,,,,",
      "Camille Alexander,Biz Ops/Office Ops,Brendan McG,Erin Dertouzos,,,,,,,",
      "Pamela Rook,Community,Andrew Williams,Bryan Velzy,Samantha Schwartz,Coralie Pachaud,,,,,"
        )
}
